cmake_minimum_required(VERSION 3.0.2)
project(lib_walking)
# set(PROJECT_DESCRIPTION "lib tasks")
# set(PROJECT_URL "url")
# include(cmake/base.cmake)
# include(cmake/cpack.cmake)
# include(cmake/cython/cython.cmake)
# include(cmake/msvc-specific.cmake)
set(CMAKE_BUILD_TYPE Release)
find_package(catkin REQUIRED)
find_package(Boost REQUIRED COMPONENTS system)
find_package(Boost REQUIRED COMPONENTS serialization)
find_package(Boost REQUIRED COMPONENTS timer)
find_package(Eigen3 REQUIRED)
catkin_package(
)
add_subdirectory(SpaceVecAlg)
add_subdirectory(RBDyn)
add_subdirectory(eigen-qld)
add_subdirectory(sch-core)
# include_directories(
#   ${CMAKE_CURRENT_SOURCE_DIR}/lib/sch-core/include/
# )
add_subdirectory(Tasks)
add_subdirectory(osqp)
