/*
 * This file has been automatically generated by the jrl-cmakemodules.
 * Please see https://github.com/jrl-umi3218/jrl-cmakemodules/blob/master/config.hh.cmake for details.
*/

#ifndef SPACEVECALG_CONFIG_HH
# define SPACEVECALG_CONFIG_HH

// Package version (header).
# define SPACEVECALG_VERSION_UNKNOWN_TAG 0 // Used to mention that the current version is unknown.
# define SPACEVECALG_VERSION "1.2.3"
# define SPACEVECALG_MAJOR_VERSION 1
# define SPACEVECALG_MINOR_VERSION 2
# define SPACEVECALG_PATCH_VERSION 3

#define SPACEVECALG_VERSION_AT_LEAST(major, minor, patch) (SPACEVECALG_MAJOR_VERSION>major || (SPACEVECALG_MAJOR_VERSION>=major && \
                                                             (SPACEVECALG_MINOR_VERSION>minor || (SPACEVECALG_MINOR_VERSION>=minor && \
                                                                                                     SPACEVECALG_PATCH_VERSION>=patch))))

#define SPACEVECALG_VERSION_AT_MOST(major, minor, patch) (SPACEVECALG_MAJOR_VERSION<major || (SPACEVECALG_MAJOR_VERSION<=major && \
                                                            (SPACEVECALG_MINOR_VERSION<minor || (SPACEVECALG_MINOR_VERSION<=minor && \
                                                                                                     SPACEVECALG_PATCH_VERSION<=patch))))

// Handle portable symbol export.
// Defining manually which symbol should be exported is required
// under Windows whether MinGW or MSVC is used.
//
// The headers then have to be able to work in two different modes:
// - dllexport when one is building the library,
// - dllimport for clients using the library.
//
// On Linux, set the visibility accordingly. If C++ symbol visibility
// is handled by the compiler, see: http://gcc.gnu.org/wiki/Visibility
# if defined _WIN32 || defined __CYGWIN__
// On Microsoft Windows, use dllimport and dllexport to tag symbols.
#  define SPACEVECALG_DLLIMPORT __declspec(dllimport)
#  define SPACEVECALG_DLLEXPORT __declspec(dllexport)
#  define SPACEVECALG_DLLLOCAL
# else
// On Linux, for GCC >= 4, tag symbols using GCC extension.
#  if __GNUC__ >= 4
#   define SPACEVECALG_DLLIMPORT __attribute__ ((visibility("default")))
#   define SPACEVECALG_DLLEXPORT __attribute__ ((visibility("default")))
#   define SPACEVECALG_DLLLOCAL  __attribute__ ((visibility("hidden")))
#  else
// Otherwise (GCC < 4 or another compiler is used), export everything.
#   define SPACEVECALG_DLLIMPORT
#   define SPACEVECALG_DLLEXPORT
#   define SPACEVECALG_DLLLOCAL
#  endif // __GNUC__ >= 4
# endif // defined _WIN32 || defined __CYGWIN__

# ifdef SPACEVECALG_STATIC
// If one is using the library statically, get rid of
// extra information.
#  define SPACEVECALG_DLLAPI
#  define SPACEVECALG_LOCAL
# else
// Depending on whether one is building or using the
// library define DLLAPI to import or export.
#  ifdef spacevecalg_EXPORTS
#   define SPACEVECALG_DLLAPI SPACEVECALG_DLLEXPORT
#  else
#   define SPACEVECALG_DLLAPI SPACEVECALG_DLLIMPORT
#  endif // SPACEVECALG_EXPORTS
#  define SPACEVECALG_LOCAL SPACEVECALG_DLLLOCAL
# endif // SPACEVECALG_STATIC
#endif //! SPACEVECALG_CONFIG_HH
