/* 
 * This file has been automatically generated by the jrl-cmakemodules.
 * Please see https://github.com/jrl-umi3218/jrl-cmakemodules/blob/master/config.hh.cmake for details.
*/

#ifndef TASKS_CONFIG_HH
# define TASKS_CONFIG_HH

// Package version (header).
# define TASKS_VERSION_UNKNOWN_TAG 0 // Used to mention that the current version is unknown.
# define TASKS_VERSION "1.3.1"
# define TASKS_MAJOR_VERSION 1
# define TASKS_MINOR_VERSION 3
# define TASKS_PATCH_VERSION 1

#define TASKS_VERSION_AT_LEAST(major, minor, patch) (TASKS_MAJOR_VERSION>major || (TASKS_MAJOR_VERSION>=major && \
                                                             (TASKS_MINOR_VERSION>minor || (TASKS_MINOR_VERSION>=minor && \
                                                                                                     TASKS_PATCH_VERSION>=patch))))

#define TASKS_VERSION_AT_MOST(major, minor, patch) (TASKS_MAJOR_VERSION<major || (TASKS_MAJOR_VERSION<=major && \
                                                            (TASKS_MINOR_VERSION<minor || (TASKS_MINOR_VERSION<=minor && \
                                                                                                     TASKS_PATCH_VERSION<=patch))))

// Handle portable symbol export.
// Defining manually which symbol should be exported is required
// under Windows whether MinGW or MSVC is used.
//
// The headers then have to be able to work in two different modes:
// - dllexport when one is building the library,
// - dllimport for clients using the library.
//
// On Linux, set the visibility accordingly. If C++ symbol visibility
// is handled by the compiler, see: http://gcc.gnu.org/wiki/Visibility
# if defined _WIN32 || defined __CYGWIN__
// On Microsoft Windows, use dllimport and dllexport to tag symbols.
#  define TASKS_DLLIMPORT __declspec(dllimport)
#  define TASKS_DLLEXPORT __declspec(dllexport)
#  define TASKS_DLLLOCAL
# else
// On Linux, for GCC >= 4, tag symbols using GCC extension.
#  if __GNUC__ >= 4
#   define TASKS_DLLIMPORT __attribute__ ((visibility("default")))
#   define TASKS_DLLEXPORT __attribute__ ((visibility("default")))
#   define TASKS_DLLLOCAL  __attribute__ ((visibility("hidden")))
#  else
// Otherwise (GCC < 4 or another compiler is used), export everything.
#   define TASKS_DLLIMPORT
#   define TASKS_DLLEXPORT
#   define TASKS_DLLLOCAL
#  endif // __GNUC__ >= 4
# endif // defined _WIN32 || defined __CYGWIN__

# ifdef TASKS_STATIC
// If one is using the library statically, get rid of
// extra information.
#  define TASKS_DLLAPI
#  define TASKS_LOCAL
# else
// Depending on whether one is building or using the
// library define DLLAPI to import or export.
#  ifdef tasks_EXPORTS
#   define TASKS_DLLAPI TASKS_DLLEXPORT
#  else
#   define TASKS_DLLAPI TASKS_DLLIMPORT
#  endif // TASKS_EXPORTS
#  define TASKS_LOCAL TASKS_DLLLOCAL
# endif // TASKS_STATIC
#endif //! TASKS_CONFIG_HH
